name: Publish mkdocs via GitHub Pages

on:
  push:
    branches:
      - main
      - development
    tags:
      - '*'

# De deploy pusht de gebouwde site naar de branch gh-pages.
permissions:
  contents: write

jobs:
  deploy-main:
    name: deploy main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: get tag
        id: get_commit_hash
        run: |
          echo "commit_hash=$(git describe --tags)" >> "$GITHUB_OUTPUT"

      - name: inject version
        run: |
          sed -i 's/development/${{ steps.get_commit_hash.outputs.commit_hash }}/g' docs/version.md

      - uses: astral-sh/setup-uv@v10

      - name: Deploy
        run: uv run --locked mkdocs gh-deploy --force
